export const VALIDATION_KEYS = {
  basic: {
    candidateType: 'wizard.profile.basic.candidateType.required',
    targetEntity: 'wizard.profile.basic.targetEntity.required',
    cvName: 'wizard.profile.basic.cv.required',
    idName: 'wizard.profile.basic.id.required',
    marriageCertificateName: 'wizard.profile.basic.marriageCertificate.required',
    birthCertificateName: 'wizard.profile.basic.birthCertificate.required',
  },
  personal: {
    fullNameAr: 'wizard.profile.personal.fullNameAr.required',
    fullNameEn: 'wizard.profile.personal.fullNameEn.required',
    qid: 'wizard.profile.personal.qid.required',
    dob: 'wizard.profile.personal.dob.required',
    nationality: 'wizard.profile.personal.nationality.required',
    gender: 'wizard.profile.personal.gender.required',
    religion: 'wizard.profile.personal.religion.required',
    marital: 'wizard.profile.personal.marital.required',
    disabilityDetails: 'wizard.profile.personal.disabilityDetails.required',
    sponsorType: 'wizard.profile.personal.sponsorType.required',
    sponsorEmployerName: 'wizard.profile.personal.sponsorEmployerName.required',
    sponsorEmployerNumber: 'wizard.profile.personal.sponsorEmployerNumber.required',
    sponsorCardName: 'wizard.profile.personal.sponsorCard.required',
  },
  contact: {
    country: 'wizard.profile.contact.country.required',
    dialCode: 'wizard.profile.contact.dialCode.required',
    phone: 'wizard.profile.contact.phone.required',
    phoneVerified: 'wizard.profile.contact.phoneVerified.required',
    email: 'wizard.profile.contact.email.required',
    emailVerified: 'wizard.profile.contact.emailVerified.required',
    address: 'wizard.profile.contact.address.required',
  },
} as const;
