namespace Application.Operation.Templates.ChangeJobStatusApprovedNotification;

public sealed record ChangeJobStatusApprovedNotification;
public sealed record ChangeJobStatusApprovedNotificationModel(string JobTitle);
