import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { ButtonModule } from 'primeng/button';
import { DialogService } from 'primeng/dynamicdialog';
import { IconFieldModule } from 'primeng/iconfield'; import { InputIconModule } from 'primeng/inputicon'; import { InputTextModule } from 'primeng/inputtext';
import { Select } from 'primeng/select'; import { TableModule } from 'primeng/table'; import { TagModule } from 'primeng/tag';
import { debounceTime, distinctUntilChanged, finalize, forkJoin, Subject } from 'rxjs';
import { AuthService } from '../../../../core/auth/auth.service'; import { Permissions } from '../../../../core/constants/permissions';
import { Lang, LanguageService } from '../../../../core/services/language.service'; import { NotificationService } from '../../../../core/services/notification.service';
import { PageFiltersComponent } from '../../../../shared/components/page-filters/page-filters.component'; import { PaginationComponent } from '../../../../shared/components/pagination/pagination.component';
import { I18nNamespaceDirective } from '../../../../shared/directives/i18n-namespace.directive'; import { HasPermissionDirective } from '../../../../shared/directives/has-permission.directive';
import { dropdownOptionsModel } from '../../../../shared/models/dropdown-options.model';
import { CreateQuestionBankRequestDialogComponent } from './dialogs/create-question-bank-request/create-question-bank-request.dialog.component';
import { QuestionBankRequestFilters, QuestionBankRequestListItem } from './models/question-bank-request.models'; import { QuestionBankRequestsService } from './services/question-bank-requests.service';

@Component({ selector: 'app-question-bank-requests', standalone: true, templateUrl: './question-bank-requests.page.html', styleUrls: ['./question-bank-requests.page.scss'],
 imports: [CommonModule, FormsModule, TranslatePipe, I18nNamespaceDirective, HasPermissionDirective, PageFiltersComponent, PaginationComponent, ButtonModule, Select, TableModule, TagModule, IconFieldModule, InputIconModule, InputTextModule], providers: [DialogService] })
export class QuestionBankRequestsPage implements OnInit {
 private readonly service=inject(QuestionBankRequestsService); private readonly dialogs=inject(DialogService); private readonly translate=inject(TranslateService); private readonly notification=inject(NotificationService); private readonly language=inject(LanguageService); private readonly destroyRef=inject(DestroyRef); private readonly route=inject(ActivatedRoute); private readonly router=inject(Router); private readonly auth=inject(AuthService); private readonly changes$=new Subject<string>();
 readonly rows=signal<QuestionBankRequestListItem[]>([]); readonly loading=signal(false); readonly total=signal(0); readonly filters=signal<QuestionBankRequestFilters>({pageNumber:1,pageSize:10}); readonly currentLang=signal<Lang>(this.language.get()); readonly advanced=signal(false); readonly types=signal<dropdownOptionsModel[]>([]); readonly managements=signal<dropdownOptionsModel[]>([]); readonly jobs=signal<dropdownOptionsModel[]>([]); readonly requestTypes=signal<dropdownOptionsModel[]>([]); readonly statuses=signal<dropdownOptionsModel[]>([]); protected readonly Permissions=Permissions;
 search=''; statusId?:string; requestTypeId?:string; bankTypeId?:string; managementId?:string; jobTitleId?:string;
 private openCreateFromQuery = false;
 ngOnInit():void { this.changes$.pipe(debounceTime(500),distinctUntilChanged(),takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.apply()); this.language.current$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(x=>this.currentLang.set(x)); this.openCreateFromQuery=this.route.snapshot.queryParamMap.get('action')==='create'; this.loadLookups(); }
 openCreate():void { const ref=this.dialogs.open(CreateQuestionBankRequestDialogComponent,{header:this.translate.instant('QUESTION_BANK_REQUESTS.CREATE_TITLE'),width:'720px',modal:true,closable:true,dismissableMask:false,breakpoints:{'768px':'95vw'},data:{questionBankTypes:this.types(),managements:this.managements(),jobTitles:this.jobs()}}); ref?.onClose.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(id=>{if(id){this.notification.success(this.translate.instant('QUESTION_BANK_REQUESTS.SUCCESS'));this.load();}}); }
 onSearch():void{this.changes$.next(this.search);} apply():void{this.filters.update(f=>({...f,pageNumber:1,search:this.search.trim()||undefined,statusId:this.statusId,requestTypeId:this.requestTypeId,questionBankTypeId:this.bankTypeId,managementId:this.managementId,jobTitleId:this.jobTitleId}));this.load();} clear():void{this.search='';this.statusId=this.requestTypeId=this.bankTypeId=this.managementId=this.jobTitleId=undefined;this.apply();} page(n:number):void{this.filters.update(f=>({...f,pageNumber:n}));this.load();} pageSize(n:number):void{this.filters.update(f=>({...f,pageNumber:1,pageSize:n}));this.load();} name(ar?:string|null,en?:string|null):string{return(this.currentLang()==='ar'?ar:en)||'-';} option(x:dropdownOptionsModel):string{return x.name;} advancedCount():number{return Number(!!this.requestTypeId)+Number(!!this.bankTypeId)+Number(!!this.managementId)+Number(!!this.jobTitleId);}
 private loadLookups():void{forkJoin({types:this.service.questionBankTypes(),managements:this.service.managements(),jobs:this.service.jobTitles(),requestTypes:this.service.requestTypes(),statuses:this.service.statuses()}).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({next:x=>{this.types.set(x.types);this.managements.set(x.managements);this.jobs.set(x.jobs);this.requestTypes.set(x.requestTypes);this.statuses.set(x.statuses);this.load();if(this.openCreateFromQuery){this.openCreateFromQuery=false;if(this.auth.hasPermission(Permissions.QuestionBankRequests.Create))this.openCreate();void this.router.navigate([],{relativeTo:this.route,queryParams:{action:null},queryParamsHandling:'merge',replaceUrl:true});}},error:()=>this.notification.error(this.translate.instant('QUESTION_BANK_REQUESTS.LOAD_ERROR'))});}
 private load():void{this.loading.set(true);this.service.list(this.filters()).pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:x=>{this.rows.set(x.items??[]);this.total.set(x.metadata?.totalCount??0);},error:()=>this.notification.error(this.translate.instant('QUESTION_BANK_REQUESTS.LOAD_ERROR'))});}
}
