<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Tawtheef.Domain</RootNamespace>
        <AssemblyName>Tawtheef.Domain</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CSharpFunctionalExtensions" />
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Events\" />
      <Folder Include="ValueObjects\" />
    </ItemGroup>

</Project>
