<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Tawtheef.Domain</RootNamespace>
        <AssemblyName>Tawtheef.Domain</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" />
        <PackageReference Include="Cortex.Mediator" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ValueObjects\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Constants\SystemRoles.cs" />
    </ItemGroup>

</Project>
