import { GUID } from '../../../../../shared/types/guid.type';
import { JobCondition } from './job-condition.model';
import { JobDegree } from './job-degree.model';
import { JobRequiredAttachment } from './required-attachment.model';
import { JobResponsibility } from './job-responsibility.model';
import { JobSkill } from './job-skill.model';
import { JobPointsCopy } from './job-points-copy.model';

export interface JobCopyTemplate {
  jobTitleId: GUID;
  jobTitleAr?: string;
  jobTitleEn?: string;
  jobNumber?: string;
  sectorId: GUID;
  managementId: GUID;
  departmentId: GUID | null;
  yearsOfExperience: number;
  jobCategoryId: GUID;
  workLocationId: GUID;
  genderId?: GUID | null;
  majorId: GUID | null;
  subMajorId?: GUID | null;
  workTypeId: GUID;
  numberOfVacancies?: number | null;
  closingDate?: Date | null;
  minimumAge: number;
  maximumAge: number;
  overviewAr?: string | null;
  overviewEn?: string | null;
  benefitsAr?: string | null;
  benefitsEn?: string | null;
  qualificationsDescriptionAr?: string | null;
  qualificationsDescriptionEn?: string | null;
  degrees?: JobDegree[];
  conditions?: JobCondition[];
  responsibilities?: JobResponsibility[];
  skills?: JobSkill[];
  requiredAttachments?: JobRequiredAttachment[];
  jobPoints?: JobPointsCopy | null;
}
