import { dropdownOptionsModel } from "../../../../../shared/models/dropdown-options.model";
import { GUID } from "../../../../../shared/types/guid.type";
import { JobConditionResponse } from "./job-condition-response.model";
import { JobDegreeResponse } from "./job-degree-response.model";
import { JobPointsResponse } from "./job-points-response";
import { JobRequiredAttachmentResponse } from "./job-required-attachment-response.model";
import { JobResponsibilityResponse } from "./job-responsibility-response.model";
import { JobSkillResponse } from "./job-skill-response.model";
import { JobTabReviewNoteResponse } from "./job-tab-review-note-response";
import { JobSpecializationResponse } from "./job-specialization-response.model";

export interface JobResponse {
  id: GUID;
  jobTitleId: GUID;
  rowVersion: string;
  titleAr?: string;
  titleEn?: string;
  jobNumber?: string;
  numberOfVacancies: number;
  closingDate: Date;
  minimumAge: number;
  maximumAge: number;
  yearsOfExperience: number;
  createdDate: Date;
  updatedDate?: Date;
  createdByName: string;
  lastActionDate: Date;
  overViewAr?: string;
  overViewEn?: string;
  benefitsAr?: string;
  benefitsEn?: string;
  qualificationDescriptionAr?: string;
  qualificationDescriptionEn?: string;
  approveNote?: string;
  rejectNote?: string;
  sector: dropdownOptionsModel;
  management: dropdownOptionsModel;
  department?: dropdownOptionsModel;
  jobCategory: dropdownOptionsModel;
  gender?: dropdownOptionsModel;
  workLocation: dropdownOptionsModel;
  major: dropdownOptionsModel;
  subMajor?: dropdownOptionsModel;
  workType: dropdownOptionsModel;
  jobStatus: dropdownOptionsModel;
  jobPoints: JobPointsResponse;
  degrees: JobDegreeResponse[];
  jobSpecializations?: JobSpecializationResponse[];
  conditions: JobConditionResponse[];
  skills: JobSkillResponse[];
  responsibilities: JobResponsibilityResponse[];
  requiredAttachments: JobRequiredAttachmentResponse[];
  tabReviewNotes?: JobTabReviewNoteResponse[];
  allowedEdit: boolean;
  allowedEditPoints: boolean;
  allowedViewPoints: boolean;
  createdById?: GUID;
}
