<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" />
        <PackageReference Include="Azure.Identity" />
        <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
        <PackageReference Include="Google.Apis.Auth" />
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="reCAPTCHA.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.ApplicationInsights" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\api\specification.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\PublishProfiles\App-Tawtheef-Recruitment-Api-Dev-01 - Zip Deploy.pubxml" />
      <None Remove="Properties\PublishProfiles\App-Tawtheef-Recruitment-Web-Dev-01 - Zip Deploy.pubxml" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="appsettings.Development.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="appsettings.Producation.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="appsettings.Stage.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="appsettings.PreStage.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
